pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                script {
                    echo 'Starting Build Stage...'
                    sh 'g++ -o PES1UG22CS512-1 main.cpp'
                }
            }
        }
        
        stage('Test') {
            steps {
                script {
                    echo 'Starting Test Stage...'
                    sh './PES1UG22CS512-1'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                script {
                    echo 'Starting Deploy Stage...'
                    echo 'Deployment stage executed successfully'
                }
            }
        }
    }
    
    post {
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
